[package]
name = "tokio-amqp"
version = "0.1.3"
edition = "2018"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "lapin integration with tokio"
repository = "https://github.com/CleverCloud/lapin"
readme = "README.md"
documentation = "https://docs.rs/tokio-amqp"
keywords = ["amqp", "rabbitmq", "mio", "futures", "tokio"]
categories = ["database"]
license = "MIT"

[features]
default = ["lapin/default"]

[dependencies.lapin]
version = "^1.2.1"
path = ".."
default-features = false

[dependencies.tokio]
version = "^0.2"
default-features = false
features = ["blocking", "rt-core"]

[dev-dependencies]
tracing = "^0.1"

[dev-dependencies.tokio]
version = "^0.2"
default-features = false
features = ["blocking", "macros", "rt-core", "rt-threaded"]

[dev-dependencies.tracing-subscriber]
version = "^0.2"
features = ["fmt"]
