language: rust

cache: cargo

rust:
  - nightly
  - beta
  - stable


services: rabbitmq

before_install:
  - export ROOT_PATH=`pwd`
  - wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.0.0_1.0.2g-1ubuntu4.6_amd64.deb
  - wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl-dev_1.0.2g-1ubuntu4.6_amd64.deb
  - sudo dpkg -i libssl1.0.0_1.0.2g-1ubuntu4.6_amd64.deb
  - sudo dpkg -i libssl-dev_1.0.2g-1ubuntu4.6_amd64.deb

before_script:
  - cargo install cargo-travis --force
  - export PATH=$HOME/.cargo/bin:$PATH;

script:
  - cd $ROOT_PATH/async   && cargo build
  - cd $ROOT_PATH/async   && cargo test
  - cd $ROOT_PATH/futures && cargo build
  - cd $ROOT_PATH/futures && cargo test

after_success:
  - cargo coveralls


dist: trusty
#sudo: false

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a8be0f69e0165e590dcb
    on_success: change
    on_failure: always
    on_start:   never
