[package]
name = "lapin"
version = "0.26.6"
edition = "2018"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "AMQP client library"
repository = "https://github.com/sozu-proxy/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin"
keywords = ["amqp", "rabbitmq", "mio", "futures"]
categories = ["database"]
license = "MIT"
build = "build.rs"

[workspace]
members = [".", "futures/"]

[features]
default    = ["native-tls"]
native-tls = ["amq-protocol/native-tls"]
openssl    = ["amq-protocol/openssl"]
rustls     = ["amq-protocol/rustls"]
tokio      = ["amq-protocol/tokio"]

[build-dependencies]
amq-protocol-codegen = "^2.2"
serde_json = "^1.0"

[dependencies.amq-protocol]
version = "^2.2"
default-features = false

[dependencies.futures]
package = "futures-preview"
version = "=0.3.0-alpha.17"
optional = true

[dependencies]
failure = { version = "^0.1", default-features = false, features = ["std"] }
log = "^0.4"
mio = "^0.6"
parking_lot = '^0.9'

[dev-dependencies]
env_logger = "^0.6"
runtime = "^0.3.0-alpha.6"

[[example]]
name = "pubsub_futures"
required-features = ["futures"]
