[package]
name = "lapin"
version = "0.27.0-beta.5"
edition = "2018"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "AMQP client library"
repository = "https://github.com/sozu-proxy/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin"
keywords = ["amqp", "rabbitmq", "mio", "futures"]
categories = ["database"]
license = "MIT"
build = "build.rs"

[workspace]
members = [".", "futures/"]

[features]
default    = ["native-tls"]
native-tls = ["amq-protocol/native-tls"]
openssl    = ["amq-protocol/openssl"]
rustls     = ["amq-protocol/rustls"]
tokio      = ["amq-protocol/tokio"]

[build-dependencies]
amq-protocol-codegen = "=3.0.0-beta.2"
serde_json = "^1.0"

[dependencies.amq-protocol]
version = "=3.0.0-beta.2"
default-features = false

[dependencies.futures]
package = "futures-preview"
version = "=0.3.0-alpha.18"
optional = true

[dependencies]
log = "^0.4"
mio = "^0.6"
parking_lot = '^0.9'

[dev-dependencies]
env_logger = "^0.6"
runtime = "=0.3.0-alpha.7"
tcp-stream = "^0.7"

[[example]]
name = "custom_tls_connection"
required-features = ["native-tls"]

[[example]]
name = "pubsub_futures"
required-features = ["futures"]
