[package]
name = "lapin"
version = "1.10.0"
edition = "2018"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "AMQP client library"
repository = "https://github.com/CleverCloud/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin"
keywords = ["amqp", "rabbitmq", "mio", "futures"]
categories = ["database"]
license = "MIT"
build = "build.rs"

[features]
default                   = ["native-tls"]
codegen                   = ["codegen-internal", "amq-protocol/codegen"]
codegen-internal          = ["amq-protocol-codegen", "serde_json"]
native-tls                = ["amq-protocol/native-tls"]
openssl                   = ["amq-protocol/openssl"]
rustls                    = ["rustls-native-certs"]
rustls-native-certs       = ["amq-protocol/rustls-native-certs"]
rustls-webpki-roots-certs = ["amq-protocol/rustls-webpki-roots-certs"]
vendored-openssl          = ["amq-protocol/vendored-openssl"]

[workspace]
members = [".", "async-global-executor", "async-lapin", "async-std", "bastion", "lapinou", "tokio"]

[build-dependencies.amq-protocol-codegen]
version = "^6.1.0"
optional = true

[build-dependencies.serde_json]
version = "^1.0"
optional = true

[dependencies.amq-protocol]
version = "^6.1.0"
default-features = false

[dependencies.mio]
version  = "^0.7.6"
features = ["net", "os-poll"]

[dependencies.serde]
version  = "^1.0"
features = ["derive"]

[dependencies]
async-task = "^4.0"
crossbeam-channel = "^0.5"
futures-core = "^0.3"
log = "^0.4"
parking_lot = "^0.12"
pinky-swear = "^4.5"

[dev-dependencies]
async-global-executor = "^2.0"
env_logger = "^0.9"
futures-test = "^0.3"
futures-util = "^0.3"
serde_json = "^1.0"

[[example]]
name = "custom_tls_connection"
required-features = ["native-tls"]
