[package]
name = "lapin"
version = "0.28.0"
edition = "2018"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "AMQP client library"
repository = "https://github.com/sozu-proxy/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin"
keywords = ["amqp", "rabbitmq", "mio", "futures"]
categories = ["database"]
license = "MIT"
build = "build.rs"

[workspace]
members = [".", "futures/"]

[features]
default    = ["native-tls"]
native-tls = ["amq-protocol/native-tls"]
openssl    = ["amq-protocol/openssl"]
rustls     = ["amq-protocol/rustls"]
tokio      = ["amq-protocol/tokio"]

[build-dependencies]
amq-protocol-codegen = "^3.0"
serde_json = "^1.0"

[dependencies.amq-protocol]
version = "^3.0"
default-features = false

[dependencies.futures]
package = "futures-core-preview"
version = "=0.3.0-alpha.19"
optional = true

[dependencies]
crossbeam-channel = "^0.3"
log = "^0.4"
mio = "^0.6"
parking_lot = '^0.9'

[dev-dependencies]
env_logger = "^0.7"
futures-executor = { version = "^0.3.0-alpha.19", package = "futures-executor-preview" }
futures-util = { version = "^0.3.0-alpha.19", package = "futures-util-preview" }
tcp-stream = "^0.7"

[[example]]
name = "custom_tls_connection"
required-features = ["native-tls"]

[[example]]
name = "pubsub_futures"
required-features = ["futures"]
