[package]
name = "lapin"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
build = "build.rs"

[dependencies]
amq-protocol-types = "^0.4.0"
nom = "^2.1"
sasl = "*"
clippy = {version = "*", optional = true}
cookie-factory = { git = "https://github.com/geal/cookie-factory" }


[build-dependencies]
amq-protocol-types   = "^0.4.0"
amq-protocol-codegen = "^0.8.0" #{git = "https://github.com/Keruspe/amq-protocol/" }
handlebars = "*"
serde_json = "*"

[features]
default = []


