[package]
name = "lapin"
version = "1.2.5"
edition = "2018"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "AMQP client library"
repository = "https://github.com/CleverCloud/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin"
keywords = ["amqp", "rabbitmq", "mio", "futures"]
categories = ["database"]
license = "MIT"
build = "build.rs"

[features]
default                   = ["native-tls"]
codegen                   = ["codegen-internal", "amq-protocol/codegen"]
codegen-internal          = ["amq-protocol-codegen", "serde_json"]
native-tls                = ["amq-protocol/native-tls"]
openssl                   = ["amq-protocol/openssl"]
rustls                    = ["rustls-native-certs"]
rustls-native-certs       = ["amq-protocol/rustls-native-certs"]
rustls-webpki-roots-certs = ["amq-protocol/rustls-webpki-roots-certs"]
vendored-openssl          = ["amq-protocol/vendored-openssl"]

[workspace]
members = [".", "async-global-executor", "async-lapin", "async-std", "bastion", "lapinou", "tokio"]

[build-dependencies.amq-protocol-codegen]
version = "=6.0.0-rc12"
optional = true

[build-dependencies.serde_json]
version = "^1.0"
optional = true

[dependencies.amq-protocol]
version = "=6.0.0-rc12"
default-features = false

[dependencies.async-global-executor]
version = "^1.0.2"
features = ["async-io"]

[dependencies]
async-io = "^1.0"
async-trait = "^0.1"
blocking = "^1.0"
crossbeam-channel = "^0.4"
futures-lite = "^1.7"
parking_lot = "^0.11"
pinky-swear = "^4.4"
tracing = "^0.1"

[dev-dependencies]
waker-fn = "^1.1"

[dev-dependencies.tracing-subscriber]
version = "^0.2"
features = ["fmt"]

[[example]]
name = "custom_tls_connection"
required-features = ["native-tls"]
