[package]
name = "lapin"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
build = "build.rs"

[dependencies]
nom = "^2.1"
sasl = "*"
clippy = {version = "*", optional = true}
rusticata-macros = { git = "https://github.com/rusticata/rusticata-macros" }


[build-dependencies]
amq-protocol-codegen = "^0.2.0" #{git = "https://github.com/Keruspe/amq-protocol/" }
handlebars = "*"
serde_json = "*"

[features]
default = []


