[package]
name = "lapinou"
version = "0.0.0"
edition = "2018"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "Placeholder - lapin intergration with smol"
repository = "https://github.com/sozu-proxy/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapinou"
keywords = ["amqp", "rabbitmq", "mio", "futures", "smol"]
categories = ["database"]
license = "MIT"

[features]
default = ["lapin/default"]

[dependencies.lapin]
version = "1.0.0-alpha1"
path = ".."
default-features = false
