[package]
name = "lapinou"
version = "0.5.1"
edition = "2018"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "lapin integration with smol"
repository = "https://github.com/CleverCloud/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapinou"
keywords = ["amqp", "rabbitmq", "mio", "futures", "smol"]
categories = ["database"]
license = "MIT"

[features]
default = ["async-lapin/default"]

[dependencies]
async-executor = "^1.0"
smol = "^1.0"

[dependencies.async-lapin]
version = "^0.4.1"
path = "../async-lapin"
default-features = false

[dependencies.lapin]
version = "^1.4.2"
path = ".."
default-features = false

[dev-dependencies]
env_logger = "^0.8"
log = "^0.4"
