[package]
name = "lapin-async"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
description = "AMQP client library with a low level API designed for use with mio"
repository = "https://github.com/Geal/lapin/async"
keywords = ["amqp, rabbitmq", "mio"]
categories = ["database"]
license = "MIT"
build = "build.rs"

[dependencies]
amq-protocol-types = "^0.5.0"
nom = "^2.1"
sasl = "^0.3"
clippy = {version = "*", optional = true}
cookie-factory = "^0.1"


[build-dependencies]
amq-protocol-types   = "^0.5.0"
amq-protocol-codegen = "^0.10.0"
handlebars = "^0.25"
serde = "^0.9"
serde_derive = "^0.9"
serde_json = "^0.9"

[features]
default = []


