[package]
name = "lapin-async"
version = "0.2.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
description = "AMQP client library with a low level API designed for use with mio"
repository = "https://github.com/Geal/lapin/async"
readme = "README.md"
documentation = "https://docs.rs/lapin-async"
keywords = ["amqp", "rabbitmq", "mio"]
categories = ["database"]
license = "MIT"
build = "build.rs"

[dependencies]
log = "^0.3"
nom = "^2.2"
sasl = "^0.3"
cookie-factory = "^0.1"
amq-protocol-types = "^0.5.0"
clippy = {version = "^0.0.119", optional = true}


[build-dependencies]
serde = "^0.9"
serde_json = "^0.9"
handlebars = "^0.25"
serde_derive = "^0.9"
amq-protocol-types   = "^0.5.0"
amq-protocol-codegen = "^0.10.0"

[dev-dependencies]
env_logger = "^0.4"

[features]
default = []


