[package]
name = "async-lapin"
version = "0.4.0"
edition = "2018"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "lapin integration with async-io"
repository = "https://github.com/CleverCloud/lapin"
readme = "README.md"
documentation = "https://docs.rs/async-lapin"
keywords = ["amqp", "rabbitmq", "mio", "futures", "async-io"]
categories = ["database"]
license = "MIT"

[features]
default = ["lapin/default"]

[dependencies]
async-io = "^1.0"
parking_lot = "^0.11"

[dependencies.lapin]
version = "^1.2.3"
path = ".."
default-features = false

[dev-dependencies]
tracing = "^0.1"

[dev-dependencies.tracing-subscriber]
version = "^0.2"
features = ["fmt"]
