[package]
name = "lapin-futures"
version = "0.21.3"
edition = "2018"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
repository = "https://github.com/sozu-proxy/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin-futures"
description = "AMQP client library with a futures based API"
keywords = ["amqp", "rabbitmq", "futures", "tokio"]
categories = ["database"]
license = "MIT"

[features]
default    = ["native-tls"]
native-tls = ["lapin-async/native-tls"]
openssl    = ["lapin-async/openssl"]
rustls     = ["lapin-async/rustls"]

[dependencies.lapin-async]
version = "^0.21.3"
default-features = false
path = "../async"

[dependencies]
futures = "^0.1"
log = "^0.4"
parking_lot = "^0.8"

[dev-dependencies]
env_logger = "^0.6"
failure = "^0.1"
tokio = "^0.1.8"
