[package]
name = "lapin-futures"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "*"
tokio-proto = "*"
tokio-service = "*"
nom = "*"
cookie-factory = { git = "https://github.com/geal/cookie-factory" }
lapin-async = {path = "../async"}

[dev-dependencies]
env_logger = "*"
tokio-core = "*"
futures-cpupool = "*"
futures = "0.1"
nom = "*"
