[package]
name = "lapin-futures"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
repository = "https://github.com/Geal/lapin/futures"
description = "AMQP client library with a futures based API"
keywords = ["amqp", "rabbitmq", "futures", "tokio"]
categories = ["database"]
license = "MIT"

[dependencies]
futures = "0.1"
tokio-core = "^0.1"
nom = "^2.1"
cookie-factory = "^0.1"
lapin-async = "^0.1"

[dev-dependencies]
env_logger = "^0.4"
tokio-core = "^0.1"
futures = "0.1"
nom = "^2.1"
