[package]
name = "lapin-futures"
version = "0.10.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]
repository = "https://github.com/Geal/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin-futures"
description = "AMQP client library with a futures based API"
keywords = ["amqp", "rabbitmq", "futures", "tokio"]
categories = ["database"]
license = "MIT"

[dependencies]
nom = "^3.0"
log = "^0.4"
bytes = "^0.4"
futures = "^0.1"
tokio-io = "^0.1"
tokio-timer = "^0.1"
lapin-async = {version = "^0.10", path = "../async"}
cookie-factory = "^0.2"

[dev-dependencies]
nom = "^3.0"
env_logger = "^0.5"
futures = "^0.1"
rustls = "^0.12"
tokio-core = "^0.1"
tokio-rustls = "^0.5"
webpki = "^0.18.0-alpha"
webpki-roots = "^0.14"
