[package]
name = "lapin-futures"
version = "0.19.0-alpha1"
edition = "2018"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>", "Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
repository = "https://github.com/sozu-proxy/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin-futures"
description = "AMQP client library with a futures based API"
keywords = ["amqp", "rabbitmq", "futures", "tokio"]
categories = ["database"]
license = "MIT"

[dependencies]
amq-protocol = "=2.0.0-beta1"
bytes = "^0.4"
failure = "^0.1"
futures = "^0.1"
log = "^0.4"
parking_lot = "^0.7"
tokio-codec = "^0.1"
tokio-io = "^0.1"
tokio-sync = "^0.1"
tokio-timer = "^0.2"

[dependencies.lapin-async]
version = "=0.19.0-alpha1"
path = "../async"

[dev-dependencies]
env_logger = "^0.6"
tokio = "^0.1.8"
