[package]
name = "lapin-futures"
version = "0.1.0"
authors = ["Geoffroy Couprie <geo.couprie@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "^0.1"
nom = "^2.1"
cookie-factory = { git = "https://github.com/geal/cookie-factory" }
lapin-async = {path = "../async"}

[dev-dependencies]
env_logger = "^0.4"
tokio-core = "^0.1"
futures = "0.1"
nom = "^2.1"
