[package]
name = "async-amqp"
version = "0.1.6"
edition = "2018"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "lapin integration with async-std"
repository = "https://github.com/CleverCloud/lapin"
readme = "README.md"
documentation = "https://docs.rs/tokio-amqp"
keywords = ["amqp", "async-std", "rabbitmq", "mio", "futures"]
categories = ["database"]
license = "MIT"

[features]
default = ["async-lapin/default"]

[dependencies.async-std]
version = "^1.6.4"
features = ["default", "unstable"]

[dependencies.async-lapin]
version = "^0.4"
path = "../async-lapin"
default-features = false

[dependencies.lapin]
version = "^1.2.3"
path = ".."
default-features = false

[dev-dependencies]
log = "^0.4"

[dev-dependencies.async-std]
version = "^1.6.3"
features = ["attributes", "default", "unstable"]

[dev-dependencies.tracing-subscriber]
version = "^0.2"
features = ["fmt"]
