[package]
name = "lapin-async-global-executor"
version = "0.3.1"
edition = "2018"
authors = ["Marc-Antoine Perennou <Marc-Antoine@Perennou.com>"]
description = "lapin integration with async-global-executor"
repository = "https://github.com/CleverCloud/lapin"
readme = "README.md"
documentation = "https://docs.rs/lapin-async-global-executor"
keywords = ["amqp", "rabbitmq", "mio", "futures"]
categories = ["database"]
license = "MIT"

[features]
default = ["lapin/default", "async-io"]
async-io = ["async-global-executor/async-io"]

[dependencies]
blocking = "^1.0"

[dependencies.async-global-executor]
version = "^1.0"
default-features = false

[dependencies.lapin]
version = "^1.2.3"
path = ".."
default-features = false

[dev-dependencies]
log = "^0.4"

[dev-dependencies.tracing-subscriber]
version = "^0.2"
features = ["fmt"]
